### ISSUE TITLE
Image resizes when opening different tab

### ISSUE THREAD

**Issue by Theresa-S** [jo-mueller/RadiAID#13] opened 2021-08-05 08:38 UTC
That's probably a PyQt issue: The size of the main window changes everytime when a new tab is clicked or when some functions (e.g., image display, etc) change the size of single widgets. Not super import, but mildly annoying.

**Comment by jo-mueller** [comment] 2021-08-05 12:36
Fixed in b5ec1651e2344a3d3548dc42b0c8c9d974551d6d

**Comment by jo-mueller** [comment] 2021-08-05 12:36
Root cause: Minimum sizes for main window had to be provided in Qt designer.

**Closed as completed by jo-mueller** 2021-08-05 12:36 UTC
Labels: bug
