### ISSUE TITLE
Overlay image and isocenter spot not wiped

### ISSUE THREAD

**Issue by Theresa-S** [jo-mueller/RadiAID#12] opened 2021-08-05 08:35 UTC
When a new isocenter/mouse is loaded, it seems like the overlay image is not wiped clean. This looks troublesome and should be adressed. Especially the old isocenter crosshair is still painted into the image, so it's impossible to see which is the correct (i.e., new) one.

**Comment by jo-mueller** [comment] 2021-08-05 12:38
Root cause: The Display object containers for the image overlay were not connected to the workflow step that is attached to the loading of Plan/Radiography images.

Fixed in ee3706a1782110b2bb76277fc8221548b514a384

**Closed as completed by jo-mueller** 2021-08-05 12:38 UTC
Labels: bug
